---
- name: Undeploy Webservers
  hosts: webservers
  become: true

  tasks:
    - name: Shut down Apache
      service: 
        name: httpd
        enabled: false
        state: stopped
    - name: Remove Packages
      yum:
        name: httpd
        state: absent
